CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "btree_gin";

CREATE SCHEMA IF NOT EXISTS finrpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA finrpa GRANT ALL ON TABLES TO finrpa;
ALTER DEFAULT PRIVILEGES IN SCHEMA finrpa GRANT ALL ON SEQUENCES TO finrpa;
ALTER DEFAULT PRIVILEGES IN SCHEMA finrpa GRANT ALL ON FUNCTIONS TO finrpa;